# Default configuration (PHANTOM paper settings)
debug: false
verbose: false
skip_existing: false
n_processes: 1
data_root_dir: "../data/raw/"
processed_data_root_dir: "../data/processed/"
# >>> Hand2Gripper >>>
hand2gripper_annotation_data_root_dir: "../data/hand2gripper_annotations/"
# <<< Hand2Gripper <<<
demo_name: "epic"

# Processing settings
mode: ["all"]  # Default processing mode
demo_num: null  # Process specific demo number (null = process all videos in the root folder)

# Additional settings
debug_cameras: ['sideview', 'birdview', 'frontview'] # Add other robomimic cameras like sideview, etc. Warning: this significantly slows down the processing time


# EPIC-KITCHENS configuration override
input_resolution: 480
output_resolution: 480
robot: "Arx5"
# robot: "UR5e"
# robot: "Kinova3"
gripper: "Robotiq85"
square: false
epic: true
bimanual_setup: "shoulders"
target_hand: "both"
constrained_hand: false
depth_for_overlay: true
render: false
camera_intrinsics: "camera/camera_intrinsics_d435.json"
camera_extrinsics: "camera/camera_extrinsics_ego_bimanual_shoulders.json"
