# Default configuration (PHANTOM paper settings)
debug: false
verbose: false
skip_existing: false
n_processes: 1
data_root_dir: "../data/raw_data/"
processed_data_root_dir: "../data/processed_data/"
demo_name: ""

# Processing settings
mode: ["bbox"]  # Default processing mode
demo_num: null  # Process specific demo number (null = process all videos in the root folder)

# Additional settings
debug_cameras: [] # Add other robomimic cameras like sideview, etc. Warning: this significantly slows down the processing time


# EPIC-KITCHENS configuration override
input_resolution: 256
output_resolution: 256
robot: "Kinova3"
gripper: "Robotiq85"
square: false
epic: true
bimanual_setup: "shoulders"
target_hand: "both"
constrained_hand: false
depth_for_overlay: false
render: false
camera_intrinsics: "camera/camera_intrinsics_epic.json"
camera_extrinsics: "camera/camera_extrinsics_ego_bimanual_shoulders.json"
